name: Delete Specific Package Version from PyPI

on:
    push:
        branches: 
            - '*'
            - '*/*'

env:
    REQUESTED_PACKAGE_NAME: premai
    REQUESTED_VERSION: 1.0.0

jobs:
    delete-package-version:
        runs-on: ubuntu-latest
        steps:
            - name: Delete specific package version from PyPI
              run: |
                curl -X DELETE -H "Authorization: token ${{ secrets.PYPI_API_TOKEN }}" https://pypi.org/pypi/${{env.REQUESTED_PACKAGE_NAME}}/${{env.REQUESTED_VERSION}}/json