name: Publish to PyPI.org
on:
  push:
    tags: ["v*"]


jobs:
  pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        run: |
          python3 -m pip install --upgrade build
          python3 -m build

      - name: Check package version
        env:
          EXPECTED_VERSION: ${{ github.ref_name }}
        run: |
          VERSION=$(grep -e "version\s*=\s*" -m 1 pyproject.toml | awk -F '"' '{print $2}')

          if [ -z "$VERSION" ]; then
            echo "Version not found"
            exit 1
          fi

          if [ "$VERSION" != "$EXPECTED_VERSION" ]; then
            echo "Version $VERSION matches the branch/tag name $EXPECTED_VERSION."
            exit 1
          else

#      - name: Publish package
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.PYPI_TOKEN }}